### ISSUE TITLE
Why do you need dob?

### ISSUE THREAD

**Issue by mendelsphotography** [spacebarchat/client#127]
Just wondering from a privacy standpoint why is DOB needed to sign up?
Is this not supposed to be more private?

**Comment by MaddyUnderStars** [comment]
https://docs.fosscord.com/setup/server/configuration/

You can configure your instance to not require date of birth if you wish. The official instance mostly just uses default config.
You can always just lie about your age on the internet, too

**Comment by MaddyUnderStars** [comment]
Ah I didn't check what repo this was on. For now the default instance the client connects to is out official one, but you can change that. https://docs.fosscord.com/setup/clients/

**Comment by mendelsphotography** [comment]
i get it but still. Was thinking an open source project would remove that.
Is there an app besides the web?
Seems like out of the box cant do much.

**Comment by MaddyUnderStars** [comment]
Our client is very work in progress. You can check out our announcements in the discord.com guild for more information.
It's not exactly production ready and does not show the full feature set of the server.

Edit: And yes, you can always use a different compatible client.

**Comment by mendelsphotography** [comment]
intresting Just heard of this and seems intresting
