### ISSUE TITLE
Solved the issue with windows build 

### ISSUE THREAD

**Issue by Shiberal** [spacebarchat/client#136]
rnw-dependencies.ps1  (with clean vscode 2022 installation without packages) as Admin.
manually add  Windows SDK version 10.0.18362.0 with visual studio installer if running windows 11 at least

.\client\windows\spacebar\   rename fosscord.vcxproj to spacebar.vcxproj

**Comment by Puyodead1** [comment]
We are no longer working on the react native version of the client at this time. Development has moved to the react branch.
