### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by ghost** [spacebarchat/client#137]
Hello all! I had an error building the project. Here are the specifications of my machine:

CPU: AMD Ryzen 9 3900X
RAM: 48GB DDR4 @ 3200
OS: Windows 10 Pro
Version: 22H2
OS Build: 19045.2846

I tried Powershell, Command Prompt, and Powershell inside Visual Studio Code, all gave the same error. Here is the short version: 
[VS 2022 install glitch.docx](https://github.com/spacebarchat/client/files/11413796/VS.2022.install.glitch.docx)
And here is the version with --logging enabled: 
[VS 2022 logged glitch.docx](https://github.com/spacebarchat/client/files/11413797/VS.2022.logged.glitch.docx)

Let me know if there's anything else I can do or provide to help address the issue!

**Comment by MaddyUnderStars** [comment]
https://docs.spacebar.chat/setup/clients/
![Screenshot_20230507-130151.png](https://user-images.githubusercontent.com/46743919/236655384-16efebac-7ce1-4b86-b8ad-1232c73d6f01.png)
