### ISSUE TITLE
Somebody forgot to rename the folders to Spacebar under the "windows" directory. 

### ISSUE THREAD

**Issue by egonaut** [spacebarchat/client#138]
Just a heads up. Manually renaming solved all issues. Don't know if that's the reason for the "Windows support is currently broken." admonition or not, but my client does successfully build just fine under Windows, although to be fair I made a lot of different changes before attempting it.

**Comment by MaddyUnderStars** [comment]
@Puyodead1 lol

**Comment by Puyodead1** [comment]
> Just a heads up. Manually renaming solved all issues. Don't know if that's the reason for the "Windows support is currently broken." admonition or not, but my client does successfully build just fine under Windows, although to be fair I made a lot of different changes before attempting it. 

There's a reason for it saying that windows is broken, and it has nothing to do with building so I have no idea why you're even trying.

**Comment by egonaut** [comment]
> 

You feeling okay, bud?

**Comment by egonaut** [comment]
> **Don't know** if that's the reason for the "Windows support is currently broken." admonition **or not** 

> "it has nothing to do with building so I have no idea why you're even trying."

Aw geez, someone's hostile to someone simply giving information in case it was useful. Sorry I couldn't read your mind ,I'll find some other alt-discord client to work on, see ya. 

![image](https://github.com/spacebarchat/client/assets/19554314/bee1b182-3265-467b-b20b-39966ac0b042)

kek. Just put the Windows issue in the tracker so someone can fix it instead of expecting people to figure out the reason, then it won't be assumed. All I did was say it built, if that was the problem, because nobody has said what actually is the problem.

**Comment by Puyodead1** [comment]
🤣

**Comment by MaddyUnderStars** [comment]
Puyo I think you were a bit needlessly rude here?

**Comment by Puyodead1** [comment]
It says windows is broken, there shouldn't be anything to assume, just don't try using it.

And also, since you haven't noticed, react native version isn't even being worked on, and the issue is related to an external dependency.

**Comment by Puyodead1** [comment]
> Puyo I think you were a bit needlessly rude here?

What did I say that was rude? The docs say windows is broken, yet people still try to use it.

**Comment by egonaut** [comment]
> It says windows is broken, there shouldn't be anything to assume, just don't try using it.

...this is Github, when something is broken, that implies something needs to be fixed, no?

reading through the other closed issues, people *are* saying the build fails, and you just tell them it's no longer being developed, not the reason as to why it's classified as broken. 

this is the most bizarre interaction I've ever had on here lmfao

**Comment by Puyodead1** [comment]
We aren't working on the react native version anymore... and the problem means nothing because it's a dependency problem. There's no reason to try to fix something that's not going to be used

**Comment by MaddyUnderStars** [comment]
I mean, the original issue says they got it working, and they said they *were* interested in contributing. They could've made a PR to fix it

> > It says windows is broken, there shouldn't be anything to assume, just don't try using it.
> 
> ...this is Github, when something is broken, that implies something needs to be fixed, no?
> 
> reading through the other closed issues, people _are_ saying the build fails, and you just tell them it's no longer being developed, not the reason as to why it's classified as broken.
> 
> this is the most bizarre interaction I've ever had on here lmfao

The main branch is currently dead in favor if a rewrite on the react branch so little thought is being put into fixing issues on main, I guess.

**Comment by Puyodead1** [comment]
> I mean, the original issue says they got it working, and they said they *were* interested in contributing. They could've made a PR to fix it
> 
> 
> 
> > > It says windows is broken, there shouldn't be anything to assume, just don't try using it.
> 
> > 
> 
> > ...this is Github, when something is broken, that implies something needs to be fixed, no?
> 
> > 
> 
> > reading through the other closed issues, people _are_ saying the build fails, and you just tell them it's no longer being developed, not the reason as to why it's classified as broken.
> 
> > 
> 
> > this is the most bizarre interaction I've ever had on here lmfao
> 
> 
> 
> The main branch is currently dead in favor if a rewrite on the react branch so little thought is being put into fixing issues on main, I guess.

Yeah they said they got it to build, that's not even why the docs say windows is broken.

**Comment by MaddyUnderStars** [comment]
Last time I tried to build for windows I couldn't get it work tbf

**Comment by Puyodead1** [comment]
Well it built last time I worked on it. Either way it doesn't matter, that wasn't the reason for the notice plus it's a dead version as you said. Even if you get it to build, you still can't use it. Lol

**Comment by egonaut** [comment]
> We aren't working on the react native version anymore... and the problem means nothing because it's a dependency problem. There's no reason to try to fix something that's not going to be used

Okay, that's not what the admonition says, the admonition says that the windows build is **broken**, as in there is something wrong with it. That would be useful information to know. 

> Well it built last time I worked on it. Either way it doesn't matter, that wasn't the reason for the notice plus it's a dead version as you said.

Apparently the reason for the notice still didn't get across the reason for the notice if this many people have already tried to fix something that needs to be clarified multiple times. 



> > 
> 
> The main branch is currently dead in favor if a rewrite on the react branch so little thought is being put into fixing issues on main, I guess.


Thank you for the information. Good to know. Someone else posted what they did to fix the build issue as well, btw, it's one of the steps I had taken yesterday so I'm sure that was it. 

> Even if you get it to build, you still can't use it. Lol 

It's my own friendly suggestion to make it a bit more clear for other contributors.

You all have a good day .

**Comment by Puyodead1** [comment]
> > We aren't working on the react native version anymore... and the problem means nothing because it's a dependency problem. There's no reason to try to fix something that's not going to be used
> 
> 
> 
> Okay, that's not what the admonition says, the admonition says that the windows build is **broken**, as in there is something wrong with it. That would be useful information to know. 
> 
> 
> 
> > Well it built last time I worked on it. Either way it doesn't matter, that wasn't the reason for the notice plus it's a dead version as you said.
> 
> 
> 
> Apparently the reason for the notice still didn't get across the reason for the notice if this many people have already tried to fix something that needs to be clarified multiple times. 
> 
> 
> 
> 
> 
> 
> 
> > > 
> 
> > 
> 
> > The main branch is currently dead in favor if a rewrite on the react branch so little thought is being put into fixing issues on main, I guess.
> 
> 
> 
> 
> 
> Thank you for the information. Good to know. Someone else posted what they did to fix the build issue as well, btw, it's one of the steps I had taken yesterday so I'm sure that was it. 
> 
> 
> 
> > Even if you get it to build, you still can't use it. Lol 
> 
> 
> 
> It's my own friendly suggestion to make it a bit more clear for other contributors.
> 
> 
> 
> You all have a good day .

I see no reason why it needs to be clarified, it's broken and that's all the info anyone needs to know.

**Comment by egonaut** [comment]
Okay, whatever you say.
