### ISSUE TITLE
Cannot delete messages

### ISSUE THREAD

**Issue by ErrorOliver** [spacebarchat/client#151]
**Describe the bug**

**To Reproduce**
1. Go to a message in a channel (I went on a guild I owned)
2. Right click on a message
3. Click on 'Delete message'
4. Nothing happens, even then restarting client.

**Expected behavior**
The message to be deleted after it is deleted

**Console Logs**
If applicable, add console logs to help give more information about your problem.
In the console it says "should delete message" and the location of the code is `2 [0df2316d827f1221da65.js:2:2674059](https://app.spacebar.chat/0df2316d827f1221da65.js)`
**System Information (please complete the following information):**
 - OS: Windows 11 Home
 - Version (If not applicable skip): 22H2
 - Node Version: [e.g Node v18.7.0] Not sure what that means

**Env and Software info**
I don't know about these, I just used https://app.spacebar.chat/
 - Release: [e.g. 0.1.0]
 - Branch (if release is not applicable): [e.g master]
 - Commit Hash (if release is not applicable): [e.g 401eda069a3ced17f1c43294d19765663cb8dcb7]

**Additional context**

**Comment by Puyodead1** [comment]
that version of the client is no longer being developed. development is now focused on the main branch which is at https://dev.app.spacebar.chat
