### ISSUE TITLE
Spacebar client is connecting to localhost:3001 instead of the corect server.

### ISSUE THREAD

**Issue by ghost** [spacebarchat/client#188]
**Describe the bug**
When i try to register on spacebar, it tries to connect on localhost:3001

**To Reproduce**
1. Go to spacebar client on browser
2. Type the correct server ip
3. Click Register
4. Try registering as usual
5. The error appears

**Expected behavior**
Connection to the correct server.

**Console Logs**
If applicable, add console logs to help give more information about your problem.

**System Information (please complete the following information):**
 - OS: Windows 11
 - Version (If not applicable skip): [e.g Ubuntu 22.04 LTS/Windows Server 2022]
 - Node Version: Node v20.8.0

**Env and Software info**
 - Release: [e.g. 0.1.0]
 - Branch main
 - Commit Hash (if release is not applicable): 79345f7ff3907380e48b0935e14fc64ee145b786

**Comment by MaddyUnderStars** [comment]
You haven't set the public api, CDN, and gateway URLs in your server config.

**Comment by ghost** [comment]
> You haven't set the public api, CDN, and gateway URLs in your server config.

Oh, how do i do that?

**Comment by MaddyUnderStars** [comment]
In your servers config, which is by default a sqlite database file called `database.db` which you can open with tools like Sqlite db browser, in the config table there are keys called `api_publicEndpoint`, `cdn_publicEndpoint`, and `gateway_publicEndpoint`. Edit the value column of those rows to be the address clients should use to connect to your instance, wrapped in quotes. For you that will likely be the servers IP address?

For example:

API: `"http://IP_ADDR/api/v9"`
gateway: `"ws://IP_ADDR"`
CDN: `"http://IP_ADDR"`

if you're using ssl, use the secure version of these protocols. ofc if you're connecting through a local network that won't be the case.

make sure to include the quotes, as the values are parsed as JSON and the server will not start otherwise.

**Comment by ghost** [comment]
> In your servers config, which is by default a sqlite database file called `database.db` which you can open with tools like Sqlite db browser, in the config table there are keys called `api_publicEndpoint`, `cdn_publicEndpoint`, and `gateway_publicEndpoint`. Edit the value column of those rows to be the address clients should use to connect to your instance, wrapped in quotes. For you that will likely be the servers IP address?
> 
> For example:
> 
> API: `"http://IP_ADDR/api/v9"` gateway: `"ws://IP_ADDR"` CDN: `"http://IP_ADDR"`
> 
> if you're using ssl, use the secure version of these protocols. ofc if you're connecting through a local network that won't be the case.
> 
> make sure to include the quotes, as the values are parsed as JSON and the server will not start otherwise.

Oh, thank you i will try that

**Comment by ghost** [comment]
> In your servers config, which is by default a sqlite database file called `database.db` which you can open with tools like Sqlite db browser, in the config table there are keys called `api_publicEndpoint`, `cdn_publicEndpoint`, and `gateway_publicEndpoint`. Edit the value column of those rows to be the address clients should use to connect to your instance, wrapped in quotes. For you that will likely be the servers IP address?
> 
> For example:
> 
> API: `"http://IP_ADDR/api/v9"` gateway: `"ws://IP_ADDR"` CDN: `"http://IP_ADDR"`
> 
> if you're using ssl, use the secure version of these protocols. ofc if you're connecting through a local network that won't be the case.
> 
> make sure to include the quotes, as the values are parsed as JSON and the server will not start otherwise.

Update: when i tried that, this appears: https://pastebin.ubuntu.com/p/zCk82hCxRb/

**Comment by MaddyUnderStars** [comment]
I said to wrap the values in double quotes.

**Comment by ghost** [comment]
> I said to wrap the values in double quotes.

oops, my bad
