### ISSUE TITLE
pnpm build failes

### ISSUE THREAD

**Issue by CoureFire** [spacebarchat/client#191]
**Describe the bug**
"pnpm build" failes with file src/pages/subpages/ChannelPage.tsx:48:32 with error TS2322

**To Reproduce**
1. Install dependencies
2. type "pnpm build"
3. The Error apperas

**Expected behavior**
A successful spacebar client build

**Console Logs**
src/pages/subpages/ChannelPage.tsx:48:32 - error TS2322: Type '{ open: (props: PopoutOpenProps) => void; close: () => void; position: { x: number; y: number; }; element: ReactNode; isOpen: boolean; setIsOpen: Dispatch<SetStateAction<boolean>>; placement: "bottom" | ... 3 more ... | undefined; }' is not assignable to type 'Props'.
  Types of property 'position' are incompatible.
    Type '{ x: number; y: number; }' is missing the following properties from type 'DOMRect': height, width, bottom, left, and 3 more.

48     {popoutContext.element && <PopoutRenderer {...popoutContext} />}
                                  ~~~~~~~~~~~~~~


Found 1 error in src/pages/subpages/ChannelPage.tsx:48

**System Information (please complete the following information):**
 - OS: Windows 11 23H2
 - Version (If not applicable skip): [e.g Ubuntu 22.04 LTS/Windows Server 2022]
 - Node Version: Node v20.8.0

**Env and Software info**
 - Release: [e.g. 0.1.0]
 - Branch (if release is not applicable): dev
 - Commit Hash (if release is not applicable): c39e31ba75eddc5b7d161f3a58c8c8b41d34d567

**Comment by Puyodead1** [comment]
fixed in 3fcfa05c01a6c5678543ab1c0a2e495eb4f4f39e
thanks
