### ISSUE TITLE
Dates in message display weirdly when hovered over

### ISSUE THREAD

**Issue by CoureFire** [spacebarchat/client#192]
**Describe the bug**
When the text "Today at" is hovered, this appears. [screenshot attached]

**To Reproduce**
1. Hover over any message
2. The Error appears

**Expected behavior**
Correct message date to show

**System Information (please complete the following information):**
 - OS: Windows 11 23H2
 - Version (If not applicable skip): [e.g Ubuntu 22.04 LTS/Windows Server 2022]
 - Node Version: Not applicable

**Env and Software info**
 - Release: [e.g. 0.1.0]
 - Branch (if release is not applicable): [e.g master] dev, main
 - Commit Hash (if release is not applicable): 2909d4270bf299d24c9a71726f09494ed9e71754, 3fcfa05c01a6c5678543ab1c0a2e495eb4f4f39e 
![spacebar](https://github.com/spacebarchat/client/assets/92386949/28fbd029-6dc0-4da5-ac32-9d859fc57058)

**Comment by Puyodead1** [comment]
theres nothing wrong with it, discord is the same way. 
![image](https://github.com/spacebarchat/client/assets/14828766/b840e85c-d27b-457b-a508-20546ff7c0f2)

**Comment by CoureFire** [comment]
> theres nothing wrong with it, discord is the same way. ![image](https://private-user-images.githubusercontent.com/14828766/287346562-b840e85c-d27b-457b-a508-20546ff7c0f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0NTQ1MDQsIm5iZiI6MTcwMTQ1NDIwNCwicGF0aCI6Ii8xNDgyODc2Ni8yODczNDY1NjItYjg0MGU4NWMtZDI3Yi00NTdiLWE1MDgtMjA1NDZmZjdjMGYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDE4MTAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1MWFjYThkY2Y3ZWQxNWMzNDZlZmRjMmExYWU0NWU2YTU5OTY4ZjAzMGU0YjczZGQwMmQ1YTY3Njg1NzMxMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lb2fmTKT3aTzCtlHOVfgUVujsygvc4C1roevnSKGUPw)

Are you sure? December is the month, but the number 12 is also the month.

**Comment by Puyodead1** [comment]
oh, didnt realize the issue is that they all have incorrect dates, ill look into it later

**Comment by Puyodead1** [comment]
fixed in 614061e30f8d1b5f306fc5e03a4c2baff15935c0
thanks, can't believe I didn't notice that haha
