### ISSUE TITLE
[Remove this issue] [This bug affects 2 branches] 429 "Too Many Requests"

### ISSUE THREAD

**Issue by CoureFire** [spacebarchat/client#195]
**Describe the bug**
When i updated my static files on the server, developers tools shows 429 too many requests on some js files.

**To Reproduce**
1. Go to the spacebar client on the web
2. it will load endlessly

**Expected behavior**
Functioning spacebar client

**Console Logs**
If applicable, add console logs to help give more information about your problem.

**System Information (please complete the following information):**
 - OS: Windows 11 23H2
 - Version (If not applicable skip): [e.g Ubuntu 22.04 LTS/Windows Server 2022]
 - Node Version: not applicable

**Env and Software info**
 - Release: [e.g. 0.1.0]
 - Branch (if release is not applicable): main, dev
 - Commit Hash (if release is not applicable): 937878195ac3835a735eaca7e1136003d4e31407, 5c55a001a58908c5b6d9657d227482b7079d2e0b

**Comment by Puyodead1** [comment]
that's an issue with your hosting, has nothing to do with the client.
