### ISSUE TITLE
error while loading shared libraries: libthai.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by dchmelik** [spacebarchat/client#208]
Immediately crashes and says 'spacebar: error while loading shared libraries: libthai.so.0: cannot open shared object file: No such file or directory'

1. Start spacebar.

**Expected behavior**
Start.

**System Information (please complete the following information):**
 - OS: Slackware GNU/Linux 15+current (64-bit)
 - Node Version: nodejs-20.10.0-x86_64-1

**Env and Software info**
 - Release: 0.1.1

**Comment by Puyodead1** [comment]
You have to install libthai yourself. https://github.com/tauri-apps/tauri/issues/4930

**Comment by dchmelik** [comment]
> You have to install libthai yourself. [tauri-apps/tauri#4930](https://github.com/tauri-apps/tauri/issues/4930)

It should either be compiled-in or have option to run without.

**Comment by Puyodead1** [comment]
> > You have to install libthai yourself. [tauri-apps/tauri#4930](https://github.com/tauri-apps/tauri/issues/4930)
> 
> It should either be compiled-in or have option to run without.

this is an issue with tauri, not the client itself, nothing I can do about it.
