### ISSUE TITLE
Doesn't follow Linux mouse cursor theme

### ISSUE THREAD

**Issue by mak448a** [spacebarchat/client#210]
**Describe the bug**
When moving the mouse over the window, it displays the adwaita cursor theme instead of the KDE Cursor.
![image](https://github.com/spacebarchat/client/assets/94062293/04ff8b6f-01ea-4f95-8a56-917f17487944)

**To Reproduce**
1. Open latest spacebar appimage and run on a KDE Plasma system.
2. See cursor.

**System Information (please complete the following information):**
 - OS: Fedora 39

**Env and Software info**
 - Release: client-dev_6e293a0

**Comment by Puyodead1** [comment]
This would be an issue with tauri, This is the response from the tauri team:
![image](https://github.com/spacebarchat/client/assets/14828766/e0ae20c4-50c7-4144-bd16-fd9b6323eb87)

https://github.com/tauri-apps/linuxdeploy-plugin-gtk/blob/master/linuxdeploy-plugin-gtk.sh#L181-L186

**Comment by mak448a** [comment]
Thanks for the link!
