### ISSUE TITLE
Error when using sourcemap

### ISSUE THREAD

**Issue by fvlasie** [spacebarchat/client#335]
**Describe the bug**
When running `pnpm run build` I get a whole bunch of these errors:
```
node_modules/.pnpm/@mui+material@5.16.0_@emotion+react@11.11.4_@types+react@18.3.3_react@18.3.1__@emotion+styled_yltlz3ewpw4wfnbvr7idu3hygq/node_modules/@mui/material/utils/index.js (1:0): Error when using sourcemap for reporting an error: Can't resolve original location of error.
node_modules/.pnpm/@mui+material@5.16.0_@emotion+react@11.11.4_@types+react@18.3.3_react@18.3.1__@emotion+styled_yltlz3ewpw4wfnbvr7idu3hygq/node_modules/@mui/material/styles/index.js (1:0): Error when using sourcemap for reporting an error: Can't resolve original location of error.
node_modules/.pnpm/@mui+material@5.16.0_@emotion+react@11.11.4_@types+react@18.3.3_react@18.3.1__@emotion+styled_yltlz3ewpw4wfnbvr7idu3hygq/node_modules/@mui/material/AccordionActions/AccordionActions.js (1:0): Error when using sourcemap for reporting an error: Can't resolve original location of error.
8<-----8<-----8<-----8<-----
```
**To Reproduce**
Follow the setup instructions here: https://docs.spacebar.chat/setup/clients/official/react/#official-host
at this command: `pnpm run build` the errors appear

**Expected behavior**
It should build without errors.

**Console Logs**
If applicable, add console logs to help give more information about your problem.

**System Information (please complete the following information):**
 - OS: Rocky Linux
 - Version: 8
 - Node Version: Node v18.20.3

**Env and Software info**
 - Branch (if release is not applicable): main

**Comment by Puyodead1** [comment]
They're actually just warnings, you can ignore them. It still builds fine.
https://github.com/vitejs/vite/issues/15012
