### ISSUE TITLE
Strip any and all forms of the stripe API implementation (if possible)

### ISSUE THREAD

**Issue by Levon-Volodin** [spacebarchat/client#56]
it is highly recommended to get rid of the option on the fosscord client to not include any forms of payment (unless you want to implement that in the future) i see people wanting to actually add their cards and payment methods to their fosscord instances (although the current state of the fosscord-discord temporary client is barred from the stripe API some people still might try so i highly recommend that be stripped from the upcoming fosscord client **BUT** maybe add a way to donate to the fosscord project?

**Comment by TheArcaneBrony** [comment]
If I remember correctly there were plans for payment support to finance instance owners. Not sure what the current plan is on that end but it's not a big priority to be implemented in the fosscord client anyways.

If you can give us CSS to hide the buttons for entering payment info, we'd be glad to merge it into our css customisations.

**Comment by Levon-Volodin** [comment]
> If I remember correctly there were plans for payment support to finance instance owners. Not sure what the current plan is on that end but it's not a big priority to be implemented in the fosscord client anyways.
> 
> If you can give us CSS to hide the buttons for entering payment info, we'd be glad to merge it into our css customisations.

let me see if i can try to search through the client CSS to find it

**Comment by Levon-Volodin** [comment]
heres a possible CSS code block that in theory can hide anything relating to payment methods (for now obviously)

```
.button-38aScr {
 display: none;
}
```
if this causes any problems do feel free to remove it
note: i need to review it again because now profile buttons are missing so **DO NOT MERGE THIS** xD

**Comment by TheArcaneBrony** [comment]
This selector seems like it would be overreaching.

**Comment by Levon-Volodin** [comment]
yea i would find whatever links up to payment method (buttons) and try to make it to where it displays nothing but the code block above is way too overkill because it will get rid of most buttons making the client unusable so **DONT** merge it yet

**Comment by TheArcaneBrony** [comment]
That aside, we don't have any implementation for Stripe server-side so any attempt to pay will fail regardless
