### ISSUE TITLE
How to switch server to discord.com

### ISSUE THREAD

**Issue by tungdo0602** [spacebarchat/client#69]
![image](https://user-images.githubusercontent.com/89498812/154788030-01ab2ade-6e7b-4bbd-aabc-5a953e66cf2e.png)

**Comment by ImAaronFR** [comment]
That's a feature of the client which isn't implemented yet.

**Comment by OrionCodeDev** [comment]
Any ETA?

**Comment by ImAaronFR** [comment]
> Any ETA?

_**No release date or ETA**_
