### ISSUE TITLE
How to install? Totally confused. There is no flatpak, deb, appimage or a snap?

### ISSUE THREAD

**Issue by heidiwenger** [spacebarchat/client#77]
OK so i at least found this section where its explained how Fosscord is installed: 

Installation

    [Client](https://github.com/fosscord/fosscord-client)
    [Server](https://github.com/fosscord/fosscord-server) (very early pre release)

I go to the Client section (i want the client app) and there are these instructions:

"Building

To build the project you have to install yarn (preferred) or npm.

cd fosscord-client; yarn install 

Then

yarn run"

But already the first brings obstacle as i open the terminal and put the command in: 

cd fosscord-client; yarn install 

"bash: cd: fosscord-client: No such file or directory
bash: yarn: command not found"

I'm very confused. There are no other instructions! 

Then i found this: https://app.fosscord.com/

I clicked register and put in email and password, but all it does it brings me to back to the main selection. Also the confirmation email (or anything) is not arriving?

So how can i install Fosscord? I'm on square zero with this and overwhelmed. I'm on Linux Mint 20.03. Thanks.

**Comment by TheArcaneBrony** [comment]
Hi! The client doesn't currently work. We recommend using a browser or a discord desktop client for now. App.fosscord.com is currently a UI demo and doesn't have any functionality. If you wanted to test fosscord, you can do so at https://dev.fosscord.com.

**Comment by heidiwenger** [comment]
> 

Ok thanks. But when i create an account and login at https://dev.fosscord.com/channels/@me -it shows "Discord" on the top bar etc? Or is this just a Discord server via Fosscord? I'm SO confused on this.

**Comment by TheArcaneBrony** [comment]
No its discord's client connecting to fosscord instead of discord's API

**Comment by oie1** [comment]
give a desktop client pls

**Comment by sairam4123** [comment]
seems like its down

**Comment by macpijan** [comment]
I was excited to see this project, and I was struggling to see how it can be started as well.

> Hi! The client doesn't currently work

Is it still the case? If so, could you please flash with some warnings on the README that this repo does not really work currently?

The https://dev.fosscord.com/ looks down.

**Comment by neu-ma-tic** [comment]
> I was excited to see this project, and I was struggling to see how it can be started as well.
> 
> > Hi! The client doesn't currently work
> 
> Is it still the case? If so, could you please flash with some warnings on the README that this repo does not really work currently?
> 
> The https://dev.fosscord.com/ looks down.

There's a guide on how to install it? The repo is fine. It's the developers. This is why selfhosted apps are selfhosted: anyone can host it, so they don't have to rely on a third party for resilience and uptime. Using applications not backed by large amounts of money or an incentive, I expect them to eventually stop being maintained and kept online, since there's no viable way to pay for it.
