### ISSUE TITLE
where is the actual client code located?

### ISSUE THREAD

**Issue by neu-ma-tic** [spacebarchat/client#98]
when building the code, all I can see is the temporary frontend, and the way to get to the actual discord-like frontend is not clear to me

**Comment by Puyodead1** [comment]
there is no "actual discord-like frontend", what you see is all there is

**Comment by neu-ma-tic** [comment]
Alright. This confused me before when I ran the server, and I thought that the server pulled from here for the frontend. Is the frontend just a build of discord with all of the css and js downloaded?

**Comment by Puyodead1** [comment]
> Is the frontend just a build of discord with all of the css and js downloaded?

yes
